# Generated by Django 5.0.6 on 2024-05-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panther_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
